base_url = "https://ekunazanu.foo"
title = "ekunazanu.foo"
description = "A blogified version of xkcd, only worse, and more personal, and not really funny."
default_language = "en"
output_dir = "deploy"
preserve_dotfiles_in_output = false
compile_sass = false
minify_html = true
ignored_content = []
ignored_static = []
generate_feeds = true
feed_filenames = ["atom.xml"]
feed_limit = 10
hard_link_static = false
author = "ekunazanu"
taxonomies = []
build_search_index = false

[markdown]
highlight_code = false
# extra_syntaxes_and_themes = []
# highlight_theme = "base16-ocean-dark"
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true
lazy_async_image = true
bottom_footnotes = false

[link_checker]
skip_prefixes = []
skip_anchor_prefixes = []
internal_level = "error"
external_level = "error"

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"
paths_keep_dates = false

[search]
# include_title = true
# include_description = true
# include_path = false
# include_content = true
# truncate_content_length = 100
# index_format = "elasticlunr_json"

[extra]
# Value will be available using {{ config.extra.param }} in templates
